title: "My Blog"
description: "A custom Jekyll blog with my own design"
baseurl: ""
url: "https://username.github.io"
theme: null   # ensures Jekyll uses your layouts
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
